<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CharacterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $characters = [
            [
                'image' => 'images/characters/rarity/6/100px-Aak_icon.webp',
                'name' => 'Aak',
                'faction' => "images/factions/120px-Lee's_Detective_Agency.webp",
                'class' => 'images/classes/50px-Specialist.png',
                'archetype' => 'images/archetypes/specialist/50px-Geek_Specialist.webp',
                'rarity' => '6★',
                'dp_cost' => 13,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Angelina_icon.webp',
                'name' => 'Angelina',
                'faction' => "images/factions/120px-Siracusa.webp",
                'class' => 'images/classes/Supporter.png',
                'archetype' => 'images/archetypes/supporter/50px-Decel_Binder_Supporter.webp',
                'rarity' => '6★',
                'dp_cost' => 16,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Archetto_icon.webp',
                'name' => 'Archetto',
                'faction' => "images/factions/120px-Laterano.webp",
                'class' => 'images/classes/50px-Sniper.png',
                'archetype' => 'images/archetypes/sniper/48px-Marksman_Sniper.webp',
                'rarity' => '6★',
                'dp_cost' => 14,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Ascalon_icon.webp',
                'name' => 'Ascalon',
                'faction' => "images/factions/120px-S.webp",
                'class' => 'images/classes/50px-Specialist.png',
                'archetype' => 'images/archetypes/specialist/50px-Ambusher_Specialist.webp',
                'rarity' => '6★',
                'dp_cost' => 21,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Ash_icon.webp',
                'name' => 'Ash',
                'faction' => "images/factions/120px-Team_Rainbow.webp",
                'class' => 'images/classes/50px-Sniper.png',
                'archetype' => 'images/archetypes/sniper/48px-Marksman_Sniper.webp',
                'rarity' => '6★',
                'dp_cost' => 14,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Bagpipe_icon.webp',
                'name' => 'Bagpipe',
                'faction' => "images/factions/120px-Victoria.webp",
                'class' => 'images/classes/50px-Vanguard.png',
                'archetype' => 'images/archetypes/vanguard/50px-Charger_Vanguard.webp',
                'rarity' => '6★',
                'dp_cost' => 13,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Blaze_icon.webp',
                'name' => 'Blaze',
                'faction' => "images/factions/120px-Elite_Op.webp",
                'class' => 'images/classes/50px-Guard.png',
                'archetype' => 'images/archetypes/guard/50px-Centurion_Guard.webp',
                'rarity' => '6★',
                'dp_cost' => 24,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Blaze_the_Igniting_Spark_icon.webp',
                'name' => 'Blaze the Igniting Spark',
                'faction' => "images/factions/120px-Elite_Op.webp",
                'class' => 'images/classes/50px-Caster.png',
                'archetype' => 'images/archetypes/caster/50px-Primal_Caster.webp',
                'rarity' => '6★',
                'dp_cost' => 21,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Blemishine_icon.webp',
                'name' => 'Blemishine',
                'faction' => "images/factions/120px-Kazimierz.webp",
                'class' => 'images/classes/49px-Defender.png',
                'archetype' => 'images/archetypes/defender/39px-Guardian_Defender.webp',
                'rarity' => '6★',
                'dp_cost' => 22,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Carnelian_icon.webp',
                'name' => 'Carnelian',
                'faction' => "images/factions/120px-Leithanien.webp",
                'class' => 'images/classes/50px-Caster.png',
                'archetype' => 'images/archetypes/caster/50px-Phalanx_Caster.webp',
                'rarity' => '6★',
                'dp_cost' => 24,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Ceobe_icon.webp',
                'name' => 'Ceobe',
                'faction' => "images/factions/120px-Rhodes_Island.webp",
                'class' => 'images/classes/50px-Caster.png',
                'archetype' => 'images/archetypes/caster/Core_Caster.webp',
                'rarity' => '6★',
                'dp_cost' => 21,
            ],
            [
                'image' => "images/characters/rarity/6/100px-Ch'en_icon.webp",
                'name' => "Ch'en",
                'faction' => "images/factions/120px-Lungmen_Guard_Department.webp",
                'class' => 'images/classes/50px-Guard.png',
                'archetype' => 'images/archetypes/guard/50px-Swordmaster_Guard.webp',
                'rarity' => '6★',
                'dp_cost' => 23,
            ],
            [
                'image' => "images/characters/rarity/6/100px-Ch'en_the_Holungday_icon.webp",
                'name' => "Ch'en the Holungday",
                'faction' => "images/factions/120px-Rhodes_Island.webp",
                'class' => 'images/classes/50px-Sniper.png',
                'archetype' => 'images/archetypes/sniper/50px-Spreadshooter_Sniper.webp',
                'rarity' => '6★',
                'dp_cost' => 32,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Chongyue_icon.webp',
                'name' => 'Chongyue',
                'faction' => "images/factions/120px-Sui.webp",
                'class' => 'images/classes/50px-Guard.png',
                'archetype' => 'images/archetypes/guard/49px-Fighter_Guard.webp',
                'rarity' => '6★',
                'dp_cost' => 11,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Civilight_Eterna_icon.webp',
                'name' => 'Civilight Eterna',
                'faction' => "images/factions/120px-Rhodes_Island.webp",
                'class' => 'images/classes/Supporter.png',
                'archetype' => 'images/archetypes/supporter/50px-Bard_Supporter.webp',
                'rarity' => '6★',
                'dp_cost' => 10,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Crownslayer_icon.webp',
                'name' => 'Crownslayer',
                'faction' => "images/factions/120px-Rhodes_Island.webp",
                'class' => 'images/classes/50px-Specialist.png',
                'archetype' => 'images/archetypes/specialist/50px-Executor_Specialist.webp',
                'rarity' => '6★',
                'dp_cost' => 12,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Degenbrecher_icon.webp',
                'name' => 'Degenbrecher',
                'faction' => "images/factions/120px-Karlan_Trade.webp",
                'class' => 'images/classes/50px-Guard.png',
                'archetype' => 'images/archetypes/guard/50px-Swordmaster_Guard.webp',
                'rarity' => '6★',
                'dp_cost' => 23,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Dorothy_icon.webp',
                'name' => 'Dorothy',
                'faction' => "images/factions/120px-Rhine_Lab.webp",
                'class' => 'images/classes/50px-Specialist.png',
                'archetype' => 'images/archetypes/specialist/50px-Trapmaster_Specialist.webp',
                'rarity' => '6★',
                'dp_cost' => 12,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Dusk_icon.webp',
                'name' => 'Dusk',
                'faction' => "images/factions/120px-Sui.webp",
                'class' => 'images/classes/50px-Caster.png',
                'archetype' => 'images/archetypes/caster/50px-Splash_Caster.webp',
                'rarity' => '6★',
                'dp_cost' => 34,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Ebenholz_icon.webp',
                'name' => 'Ebenholz',
                'faction' => "images/factions/120px-Leithanien.webp",
                'class' => 'images/classes/50px-Caster.png',
                'archetype' => 'images/archetypes/caster/50px-Mystic_Caster.webp',
                'rarity' => '6★',
                'dp_cost' => 25,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Ela_icon.webp',
                'name' => 'Ela',
                'faction' => "images/factions/120px-Team_Rainbow.webp",
                'class' => 'images/classes/50px-Specialist.png',
                'archetype' => 'images/archetypes/specialist/50px-Trapmaster_Specialist.webp',
                'rarity' => '6★',
                'dp_cost' => 12,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Entelechia_icon.webp',
                'name' => 'Entelechia',
                'faction' => "images/factions/120px-Rhodes_Island.webp",
                'class' => 'images/classes/50px-Guard.png',
                'archetype' => 'images/archetypes/guard/50px-Reaper_Guard.webp',
                'rarity' => '6★',
                'dp_cost' => 23,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Eunectes_icon.webp',
                'name' => 'Eunectes',
                'faction' => "images/factions/120px-Sargon.webp",
                'class' => 'images/classes/49px-Defender.png',
                'archetype' => 'images/archetypes/defender/38px-Duelist_Defender.webp',
                'rarity' => '6★',
                'dp_cost' => 33,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Executor_the_Ex_Foedere_icon.webp',
                'name' => 'Executor the Ex Foedere',
                'faction' => "images/factions/120px-Laterano.webp",
                'class' => 'images/classes/50px-Guard.png',
                'archetype' => 'images/archetypes/guard/50px-Reaper_Guard.webp',
                'rarity' => '6★',
                'dp_cost' => 23,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Exusiai_icon.webp',
                'name' => 'Exusiai',
                'faction' => "images/factions/120px-Penguin_Logistics.webp",
                'class' => 'images/classes/50px-Sniper.png',
                'archetype' => 'images/archetypes/sniper/48px-Marksman_Sniper.webp',
                'rarity' => '6★',
                'dp_cost' => 14,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Exusiai_the_New_Covenant_icon.webp',
                'name' => 'Exusiai the New Covenant',
                'faction' => "images/factions/120px-Penguin_Logistics.webp",
                'class' => 'images/classes/50px-Specialist.png',
                'archetype' => 'images/archetypes/specialist/50px-Geek_Specialist.webp',
                'rarity' => '6★',
                'dp_cost' => 13,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Eyjafjalla_icon.webp',
                'name' => 'Eyjafjalla',
                'faction' => "images/factions/120px-Leithanien.webp",
                'class' => 'images/classes/50px-Caster.png',
                'archetype' => 'images/archetypes/caster/Core_Caster.webp',
                'rarity' => '6★',
                'dp_cost' => 21,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Eyjafjalla_the_Hvít_Aska_icon.webp',
                'name' => 'Eyjafjalla the Hvít Aska',
                'faction' => "images/factions/120px-Leithanien.webp",
                'class' => 'images/classes/49px-Medic.png',
                'archetype' => 'images/archetypes/medic/50px-Wandering_Medic.webp',
                'rarity' => '6★',
                'dp_cost' => 16,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Fartooth_icon.webp',
                'name' => 'Fartooth',
                'faction' => "images/factions/120px-Pinus_Sylvestris.webp",
                'class' => 'images/classes/50px-Sniper.png',
                'archetype' => 'images/archetypes/sniper/49px-Deadeye_Sniper.webp',
                'rarity' => '6★',
                'dp_cost' => 22,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Fiammetta_icon.webp',
                'name' => 'Fiammetta',
                'faction' => "images/factions/120px-Laterano.webp",
                'class' => 'images/classes/50px-Sniper.png',
                'archetype' => 'images/archetypes/sniper/50px-Artilleryman_Sniper.webp',
                'rarity' => '6★',
                'dp_cost' => 29,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Flametail_icon.webp',
                'name' => 'Flametail',
                'faction' => "images/factions/120px-Pinus_Sylvestris.webp",
                'class' => 'images/classes/50px-Vanguard.png',
                'archetype' => 'images/archetypes/vanguard/50px-Pioneer_Vanguard.webp',
                'rarity' => '6★',
                'dp_cost' => 14,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Gavial_the_Invincible_icon.webp',
                'name' => 'Gavial the Invincible',
                'faction' => "images/factions/120px-Rhodes_Island.webp",
                'class' => 'images/classes/50px-Guard.png',
                'archetype' => 'images/archetypes/guard/50px-Centurion_Guard.webp',
                'rarity' => '6★',
                'dp_cost' => 24,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Gladiia_icon.webp',
                'name' => 'Gladiia',
                'faction' => "images/factions/120px-Abyssal_Hunters.webp",
                'class' => 'images/classes/50px-Specialist.png',
                'archetype' => 'images/archetypes/specialist/48px-Hookmaster_Specialist.webp',
                'rarity' => '6★',
                'dp_cost' => 16,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Gnosis_icon.webp',
                'name' => 'Gnosis',
                'faction' => "images/factions/120px-Karlan_Trade.webp",
                'class' => 'images/classes/Supporter.png',
                'archetype' => 'images/archetypes/supporter/35px-Hexer_Supporter.webp',
                'rarity' => '6★',
                'dp_cost' => 13,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Goldenglow_icon.webp',
                'name' => 'Goldenglow',
                'faction' => "images/factions/120px-Victoria.webp",
                'class' => 'images/classes/50px-Caster.png',
                'archetype' => 'images/archetypes/caster/50px-Mech-Accord_Caster.webp',
                'rarity' => '6★',
                'dp_cost' => 22,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Hellagur_icon.webp',
                'name' => 'Hellagur',
                'faction' => "images/factions/120px-Ursus.webp",
                'class' => 'images/classes/50px-Guard.png',
                'archetype' => 'images/archetypes/guard/50px-Soloblade_Guard.webp',
                'rarity' => '6★',
                'dp_cost' => 26,
            ],
            [
                'image' => "images/characters/rarity/6/100px-Ho'olheyak_icon.webp",
                'name' => "Ho'olheyak",
                'faction' => "images/factions/120px-Columbia.webp",
                'class' => 'images/classes/50px-Caster.png',
                'archetype' => 'images/archetypes/caster/Core_Caster.webp',
                'rarity' => '6★',
                'dp_cost' => 21,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Hoederer_icon.webp',
                'name' => 'Hoederer',
                'faction' => "images/factions/120px-Babel.webp",
                'class' => 'images/classes/50px-Guard.png',
                'archetype' => 'images/archetypes/guard/50px-Crusher_Guard.webp',
                'rarity' => '6★',
                'dp_cost' => 24,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Horn_icon.webp',
                'name' => 'Horn',
                'faction' => "images/factions/120px-Victoria.webp",
                'class' => 'images/classes/49px-Defender.png',
                'archetype' => 'images/archetypes/defender/43px-Fortress_Defender.webp',
                'rarity' => '6★',
                'dp_cost' => 28,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Hoshiguma_icon.webp',
                'name' => 'Hoshiguma',
                'faction' => "images/factions/120px-Lungmen_Guard_Department.webp",
                'class' => 'images/classes/49px-Defender.png',
                'archetype' => 'images/archetypes/defender/39px-Protector_Defender.webp',
                'rarity' => '6★',
                'dp_cost' => 23,
            ],
            [
                'image' => "images/characters/rarity/6/100px-Ifrit_icon.webp",
                'name' => 'Ifrit',
                'faction' => "images/factions/120px-Rhine_Lab.webp",
                'class' => 'images/classes/50px-Caster.png',
                'archetype' => 'images/archetypes/caster/49px-Blast_Caster.webp',
                'rarity' => '6★',
                'dp_cost' => 34,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Ines_icon.webp',
                'name' => 'Ines',
                'faction' => "images/factions/120px-Babel.webp",
                'class' => 'images/classes/50px-Vanguard.png',
                'archetype' => 'images/archetypes/vanguard/50px-Agent_Vanguard.webp',
                'rarity' => '6★',
                'dp_cost' => 11,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Irene_icon.webp',
                'name' => 'Irene',
                'faction' => "images/factions/120px-Iberia.webp",
                'class' => 'images/classes/50px-Guard.png',
                'archetype' => 'images/archetypes/guard/50px-Swordmaster_Guard.webp',
                'rarity' => '6★',
                'dp_cost' => 23,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Jessica_the_Liberated_icon.webp',
                'name' => 'Jessica the Liberated',
                'faction' => "images/factions/120px-Blacksteel.webp",
                'class' => 'images/classes/49px-Defender.png',
                'archetype' => 'images/archetypes/defender/40px-Sentry_Protector_Defender.webp',
                'rarity' => '6★',
                'dp_cost' => 23,
            ],
            [
                'image' => "images/characters/rarity/6/100px-Kal'Tsit_icon.webp",
                'name' => "Kal'Tsit",
                'faction' => "images/factions/120px-Rhodes_Island.webp",
                'class' => 'images/classes/49px-Medic.png',
                'archetype' => 'images/archetypes/medic/46px-Medic_Medic.webp',
                'rarity' => '6★',
                'dp_cost' => 20,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Kirin_R_Yato_icon.webp',
                'name' => 'Kirin R Yato',
                'faction' => "images/factions/120px-Op_A4.webp",
                'class' => 'images/classes/50px-Specialist.png',
                'archetype' => 'images/archetypes/specialist/50px-Executor_Specialist.webp',
                'rarity' => '6★',
                'dp_cost' => 10,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Lappland_the_Decadenza_icon.webp',
                'name' => 'Lappland the Decadenza',
                'faction' => "images/factions/120px-Siracusa.webp",
                'class' => 'images/classes/50px-Caster.png',
                'archetype' => 'images/archetypes/caster/50px-Mech-Accord_Caster.webp',
                'rarity' => '6★',
                'dp_cost' => 22,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Lee_icon.webp',
                'name' => 'Lee',
                'faction' => "images/factions/120px-Lee's_Detective_Agency.webp",
                'class' => 'images/classes/50px-Specialist.png',
                'archetype' => 'images/archetypes/specialist/50px-Merchant_Specialist.webp',
                'rarity' => '6★',
                'dp_cost' => 9,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Lemuen_icon.webp',
                'name' => 'Lemuen',
                'faction' => "images/factions/120px-Laterano.webp",
                'class' => 'images/classes/50px-Sniper.png',
                'archetype' => 'images/archetypes/sniper/49px-Deadeye_Sniper.webp',
                'rarity' => '6★',
                'dp_cost' => 22,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Lessing_icon.webp',
                'name' => 'Lessing',
                'faction' => "images/factions/120px-Leithanien.webp",
                'class' => 'images/classes/50px-Guard.png',
                'archetype' => 'images/archetypes/guard/50px-Dreadnought_Guard.webp',
                'rarity' => '6★',
                'dp_cost' => 21,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Lin_icon.webp',
                'name' => 'Lin',
                'faction' => "images/factions/120px-Lungmen.webp",
                'class' => 'images/classes/50px-Caster.png',
                'archetype' => 'images/archetypes/caster/50px-Phalanx_Caster.webp',
                'rarity' => '6★',
                'dp_cost' => 24,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Ling_icon.webp',
                'name' => 'Ling',
                'faction' => "images/factions/120px-Sui.webp",
                'class' => 'images/classes/Supporter.png',
                'archetype' => 'images/archetypes/supporter/50px-Summoner_Supporter.webp',
                'rarity' => '6★',
                'dp_cost' => 12,
            ],
            [
                'image' => "images/characters/rarity/6/100px-Logos_icon.webp",
                'name' => "Logos",
                'faction' => "images/factions/120px-Elite_Op.webp",
                'class' => 'images/classes/50px-Caster.png',
                'archetype' => 'images/archetypes/caster/Core_Caster.webp',
                'rarity' => '6★',
                'dp_cost' => 21,
            ],
            [
                'image' => "images/characters/rarity/6/100px-Lumen_icon.webp",
                'name' => "Lumen",
                'faction' => "images/factions/120px-Iberia.webp",
                'class' => 'images/classes/49px-Medic.png',
                'archetype' => 'images/archetypes/medic/47px-Therapist_Medic.webp',
                'rarity' => '6★',
                'dp_cost' => 23,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Magallan_icon.webp',
                'name' => 'Magallan',
                'faction' => "images/factions/120px-Rhine_Lab.webp",
                'class' => 'images/classes/Supporter.png',
                'archetype' => 'images/archetypes/supporter/50px-Summoner_Supporter.webp',
                'rarity' => '6★',
                'dp_cost' => 12,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Marcille_icon.webp',
                'name' => 'Marcille',
                'faction' => "images/factions/120px-Laios_Party.webp",
                'class' => 'images/classes/50px-Caster.png',
                'archetype' => 'images/archetypes/caster/50px-Splash_Caster.webp',
                'rarity' => '6★',
                'dp_cost' => 34,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Mizuki_icon.webp',
                'name' => 'Mizuki',
                'faction' => "images/factions/120px-Higashi.webp",
                'class' => 'images/classes/50px-Specialist.png',
                'archetype' => 'images/archetypes/specialist/50px-Ambusher_Specialist.webp',
                'rarity' => '6★',
                'dp_cost' => 21,
            ],
            [
                'image' => "images/characters/rarity/6/100px-Mon3tr_icon.webp",
                'name' => "Mon3tr",
                'faction' => "images/factions/120px-Rhodes_Island.webp",
                'class' => 'images/classes/49px-Medic.png',
                'archetype' => 'images/archetypes/medic/50px-Chain_Medic.webp',
                'rarity' => '6★',
                'dp_cost' => 18,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Mostima_icon.webp',
                'name' => 'Mostima',
                'faction' => "images/factions/120px-Laterano.webp",
                'class' => 'images/classes/50px-Caster.png',
                'archetype' => 'images/archetypes/caster/50px-Splash_Caster.webp',
                'rarity' => '6★',
                'dp_cost' => 34,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Mountain_icon.webp',
                'name' => 'Mountain',
                'faction' => "images/factions/120px-Columbia.webp",
                'class' => 'images/classes/50px-Guard.png',
                'archetype' => 'images/archetypes/guard/49px-Fighter_Guard.webp',
                'rarity' => '6★',
                'dp_cost' => 11,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Mudrock_icon.webp',
                'name' => 'Mudrock',
                'faction' => "images/factions/120px-Rhodes_Island.webp",
                'class' => 'images/classes/49px-Defender.png',
                'archetype' => 'images/archetypes/defender/46px-Juggernaut_Defender.webp',
                'rarity' => '6★',
                'dp_cost' => 36,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Muelsyse_icon.webp',
                'name' => 'Muelsyse',
                'faction' => "images/factions/120px-Rhine_Lab.webp",
                'class' => 'images/classes/50px-Vanguard.png',
                'archetype' => 'images/archetypes/vanguard/50px-Tactician_Vanguard.webp',
                'rarity' => '6★',
                'dp_cost' => 15,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Młynar_icon.webp',
                'name' => 'Mlynar',
                'faction' => "images/factions/120px-Kazimierz.webp",
                'class' => 'images/classes/50px-Guard.png',
                'archetype' => 'images/archetypes/guard/48px-Liberator_Guard.webp',
                'rarity' => '6★',
                'dp_cost' => 12,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Narantuya_icon.webp',
                'name' => 'Narantuya',
                'faction' => "images/factions/120px-Sargon.webp",
                'class' => 'images/classes/50px-Sniper.png',
                'archetype' => 'images/archetypes/sniper/45px-Loopshooter_Sniper.webp',
                'rarity' => '6★',
                'dp_cost' => 16,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Nearl_the_Radiant_Knight_icon.webp',
                'name' => 'Nearl the Radiant Knight',
                'faction' => "images/factions/120px-Kazimierz.webp",
                'class' => 'images/classes/50px-Guard.png',
                'archetype' => 'images/archetypes/guard/50px-Dreadnought_Guard.webp',
                'rarity' => '6★',
                'dp_cost' => 19,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Necrass_icon.webp',
                'name' => 'Necrass',
                'faction' => "images/factions/120px-Tara.webp",
                'class' => 'images/classes/50px-Caster.png',
                'archetype' => 'images/archetypes/caster/50px-Shaper_Caster.webp',
                'rarity' => '6★',
                'dp_cost' => 21,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Nian_icon.webp',
                'name' => 'Nian',
                'faction' => "images/factions/120px-Sui.webp",
                'class' => 'images/classes/49px-Defender.png',
                'archetype' => 'images/archetypes/defender/39px-Protector_Defender.webp',
                'rarity' => '6★',
                'dp_cost' => 23,
            ],
            [
                'image' => "images/characters/rarity/6/100px-Nightingale_icon.webp",
                'name' => "Nightingale",
                'faction' => "images/factions/120px-Followers.webp",
                'class' => 'images/classes/49px-Medic.png',
                'archetype' => 'images/archetypes/medic/46px-Multi-target_Medic.webp',
                'rarity' => '6★',
                'dp_cost' => 18,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Nymph_icon.webp',
                'name' => 'Nymph',
                'faction' => "images/factions/120px-Rhodes_Island.webp",
                'class' => 'images/classes/50px-Caster.png',
                'archetype' => 'images/archetypes/caster/50px-Primal_Caster.webp',
                'rarity' => '6★',
                'dp_cost' => 21,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Pallas_icon.webp',
                'name' => 'Pallas',
                'faction' => "images/factions/120px-Minos.webp",
                'class' => 'images/classes/50px-Guard.png',
                'archetype' => 'images/archetypes/guard/50px-Instructor_Guard.webp',
                'rarity' => '6★',
                'dp_cost' => 17,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Passenger_icon.webp',
                'name' => 'Passenger',
                'faction' => "images/factions/120px-Sargon.webp",
                'class' => 'images/classes/50px-Caster.png',
                'archetype' => 'images/archetypes/caster/43px-Chain_Caster.webp',
                'rarity' => '6★',
                'dp_cost' => 33,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Penance_icon.webp',
                'name' => 'Penance',
                'faction' => "images/factions/120px-Siracusa.webp",
                'class' => 'images/classes/49px-Defender.png',
                'archetype' => 'images/archetypes/defender/46px-Juggernaut_Defender.webp',
                'rarity' => '6★',
                'dp_cost' => 36,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Pepe_icon.webp',
                'name' => 'Pepe',
                'faction' => "images/factions/120px-Sargon.webp",
                'class' => 'images/classes/50px-Guard.png',
                'archetype' => 'images/archetypes/guard/50px-Earthshaker_Guard.webp',
                'rarity' => '6★',
                'dp_cost' => 20,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Phantom_icon.webp',
                'name' => 'Phantom',
                'faction' => "images/factions/120px-Victoria.webp",
                'class' => 'images/classes/50px-Specialist.png',
                'archetype' => 'images/archetypes/specialist/50px-Executor_Specialist.webp',
                'rarity' => '6★',
                'dp_cost' => 10,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Pozëmka_icon.webp',
                'name' => 'Pozëmka',
                'faction' => "images/factions/120px-Sargon.webp",
                'class' => 'images/classes/50px-Sniper.png',
                'archetype' => 'images/archetypes/sniper/50px-Heavyshooter_Sniper.webp',
                'rarity' => '6★',
                'dp_cost' => 20,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Qiubai_icon.webp',
                'name' => 'Qiubai',
                'faction' => "images/factions/120px-Yan.webp",
                'class' => 'images/classes/50px-Guard.png',
                'archetype' => 'images/archetypes/guard/50px-Lord_Guard.webp',
                'rarity' => '6★',
                'dp_cost' => 20,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Ray_icon.webp',
                'name' => 'Ray',
                'faction' => "images/factions/120px-Rim_Billiton.webp",
                'class' => 'images/classes/50px-Sniper.png',
                'archetype' => 'images/archetypes/sniper/47px-Hunter_Sniper.webp',
                'rarity' => '6★',
                'dp_cost' => 21,
            ],
            [
                'image' => "images/characters/rarity/6/100px-Reed_the_Flame_Shadow_icon.webp",
                'name' => "Reed the Flame Shadow",
                'faction' => "images/factions/120px-Tara.webp",
                'class' => 'images/classes/49px-Medic.png',
                'archetype' => 'images/archetypes/medic/46px-Incantation_Medic.webp',
                'rarity' => '6★',
                'dp_cost' => 17,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Rosa_icon.webp',
                'name' => 'Rosa',
                'faction' => "images/factions/120px-Ursus_Student_Self-Governing_Group.webp",
                'class' => 'images/classes/50px-Sniper.png',
                'archetype' => 'images/archetypes/sniper/50px-Besieger_Sniper.webp',
                'rarity' => '6★',
                'dp_cost' => 24,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Rosmontis_icon.webp',
                'name' => 'Rosmontis',
                'faction' => "images/factions/120px-Elite_Op.webp",
                'class' => 'images/classes/50px-Sniper.png',
                'archetype' => 'images/archetypes/sniper/50px-Flinger_Sniper.webp',
                'rarity' => '6★',
                'dp_cost' => 25,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Saga_icon.webp',
                'name' => 'Saga',
                'faction' => "images/factions/120px-Higashi.webp",
                'class' => 'images/classes/50px-Vanguard.png',
                'archetype' => 'images/archetypes/vanguard/50px-Pioneer_Vanguard.webp',
                'rarity' => '6★',
                'dp_cost' => 14,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Saileach_icon.webp',
                'name' => 'Saileach',
                'faction' => "images/factions/120px-Victoria.webp",
                'class' => 'images/classes/50px-Vanguard.png',
                'archetype' => 'images/archetypes/vanguard/50px-Standard_Bearer_Vanguard.webp',
                'rarity' => '6★',
                'dp_cost' => 12,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Sankta_Miksaparato_icon_icon.webp',
                'name' => 'Sankta Miksaparato',
                'faction' => "images/factions/120px-Laterano.webp",
                'class' => 'images/classes/49px-Defender.png',
                'archetype' => 'images/archetypes/defender/40px-Sentry_Protector_Defender.webp',
                'rarity' => '6★',
                'dp_cost' => 25,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Saria_icon.webp',
                'name' => 'Saria',
                'faction' => "images/factions/120px-Rhine_Lab.webp",
                'class' => 'images/classes/49px-Defender.png',
                'archetype' => 'images/archetypes/defender/39px-Guardian_Defender.webp',
                'rarity' => '6★',
                'dp_cost' => 22,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Schwarz_icon.webp',
                'name' => 'Schwarz',
                'faction' => "images/factions/120px-Siesta.webp",
                'class' => 'images/classes/50px-Sniper.png',
                'archetype' => 'images/archetypes/sniper/50px-Heavyshooter_Sniper.webp',
                'rarity' => '6★',
                'dp_cost' => 20,
            ],
            [
                'image' => "images/characters/rarity/6/100px-Shining_icon.webp",
                'name' => "Shining",
                'faction' => "images/factions/120px-Followers.webp",
                'class' => 'images/classes/49px-Medic.png',
                'archetype' => 'images/archetypes/medic/46px-Medic_Medic.webp',
                'rarity' => '6★',
                'dp_cost' => 20,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Shu_icon.webp',
                'name' => 'Shu',
                'faction' => "images/factions/120px-Sui.webp",
                'class' => 'images/classes/49px-Defender.png',
                'archetype' => 'images/archetypes/defender/39px-Guardian_Defender.webp',
                'rarity' => '6★',
                'dp_cost' => 22,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Siege_icon.webp',
                'name' => 'Siege',
                'faction' => "images/factions/120px-Glasgow.webp",
                'class' => 'images/classes/50px-Vanguard.png',
                'archetype' => 'images/archetypes/vanguard/50px-Pioneer_Vanguard.webp',
                'rarity' => '6★',
                'dp_cost' => 14,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Silence_the_Paradigmatic_icon.webp',
                'name' => 'Silence the Paradigmatic',
                'faction' => "images/factions/120px-Rhine_Lab.webp",
                'class' => 'images/classes/Supporter.png',
                'archetype' => 'images/archetypes/supporter/50px-Abjurer_Supporter.webp',
                'rarity' => '6★',
                'dp_cost' => 15,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-SilverAsh_icon.webp',
                'name' => 'SilverAsh',
                'faction' => "images/factions/120px-Karlan_Trade.webp",
                'class' => 'images/classes/50px-Guard.png',
                'archetype' => 'images/archetypes/guard/50px-Lord_Guard.webp',
                'rarity' => '6★',
                'dp_cost' => 20,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Skadi_icon.webp',
                'name' => 'Skadi',
                'faction' => "images/factions/120px-Abyssal_Hunters.webp",
                'class' => 'images/classes/50px-Guard.png',
                'archetype' => 'images/archetypes/guard/50px-Dreadnought_Guard.webp',
                'rarity' => '6★',
                'dp_cost' => 19,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Skadi_the_Corrupting_Heart_icon.webp',
                'name' => 'Skadi the Corrupting Heart',
                'faction' => "images/factions/120px-Aegir.webp",
                'class' => 'images/classes/Supporter.png',
                'archetype' => 'images/archetypes/supporter/50px-Bard_Supporter.webp',
                'rarity' => '6★',
                'dp_cost' => 8,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Specter_the_Unchained_icon.webp',
                'name' => 'Specter the Unchained',
                'faction' => "images/factions/120px-Abyssal_Hunters.webp",
                'class' => 'images/classes/50px-Specialist.png',
                'archetype' => 'images/archetypes/specialist/50px-Dollkeeper_Specialist.webp',
                'rarity' => '6★',
                'dp_cost' => 16,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Stainless_icon.webp',
                'name' => 'Stainless',
                'faction' => "images/factions/120px-Aegir.webp",
                'class' => 'images/classes/Supporter.png',
                'archetype' => 'images/archetypes/supporter/48px-Artificer_Supporter.webp',
                'rarity' => '6★',
                'dp_cost' => 19,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Surtr_icon.webp',
                'name' => 'Surtr',
                'faction' => "images/factions/120px-Rhodes_Island.webp",
                'class' => 'images/classes/50px-Guard.png',
                'archetype' => 'images/archetypes/guard/50px-Arts_Fighter_Guard.webp',
                'rarity' => '6★',
                'dp_cost' => 21,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Suzuran_icon.webp',
                'name' => 'Suzuran',
                'faction' => "images/factions/120px-Siracusa.webp",
                'class' => 'images/classes/Supporter.png',
                'archetype' => 'images/archetypes/supporter/50px-Decel_Binder_Supporter.webp',
                'rarity' => '6★',
                'dp_cost' => 16,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Swire_the_Elegant_Wit_icon.webp',
                'name' => 'Swire the Elegant Wit',
                'faction' => "images/factions/120px-Lungmen.webp",
                'class' => 'images/classes/50px-Specialist.png',
                'archetype' => 'images/archetypes/specialist/50px-Merchant_Specialist.webp',
                'rarity' => '6★',
                'dp_cost' => 9,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Texas_the_Omertosa_icon.webp',
                'name' => 'Texas the Omertosa',
                'faction' => "images/factions/120px-Penguin_Logistics.webp",
                'class' => 'images/classes/50px-Specialist.png',
                'archetype' => 'images/archetypes/specialist/50px-Executor_Specialist.webp',
                'rarity' => '6★',
                'dp_cost' => 10,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Thorns_icon.webp',
                'name' => 'Thorns',
                'faction' => "images/factions/120px-Iberia.webp",
                'class' => 'images/classes/50px-Guard.png',
                'archetype' => 'images/archetypes/guard/50px-Lord_Guard.webp',
                'rarity' => '6★',
                'dp_cost' => 20,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Thorns_the_Lodestar_icon.webp',
                'name' => 'Thorns the Lodestar',
                'faction' => "images/factions/120px-Iberia.webp",
                'class' => 'images/classes/50px-Specialist.png',
                'archetype' => 'images/archetypes/specialist/47px-Alchemist_Specialist.webp',
                'rarity' => '6★',
                'dp_cost' => 18,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Typhon_icon.webp',
                'name' => 'Typhon',
                'faction' => "images/factions/120px-Sami.webp",
                'class' => 'images/classes/50px-Sniper.png',
                'archetype' => 'images/archetypes/sniper/50px-Besieger_Sniper.webp',
                'rarity' => '6★',
                'dp_cost' => 24,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Ulpianus_icon.webp',
                'name' => 'Ulpianus',
                'faction' => "images/factions/120px-Abyssal_Hunters.webp",
                'class' => 'images/classes/50px-Guard.png',
                'archetype' => 'images/archetypes/guard/50px-Crusher_Guard.webp',
                'rarity' => '6★',
                'dp_cost' => 24,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Vigil_icon.webp',
                'name' => 'Vigil',
                'faction' => "images/factions/120px-Siracusa.webp",
                'class' => 'images/classes/50px-Vanguard.png',
                'archetype' => 'images/archetypes/vanguard/50px-Tactician_Vanguard.webp',
                'rarity' => '6★',
                'dp_cost' => 17,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Vina_Victoria_icon.webp',
                'name' => 'Vina Victoria',
                'faction' => "images/factions/120px-Victoria.webp",
                'class' => 'images/classes/50px-Guard.png',
                'archetype' => 'images/archetypes/guard/50px-Arts_Fighter_Guard.webp',
                'rarity' => '6★',
                'dp_cost' => 21,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Virtuosa_icon.webp',
                'name' => 'Virtuosa',
                'faction' => "images/factions/120px-Laterano.webp",
                'class' => 'images/classes/Supporter.png',
                'archetype' => 'images/archetypes/supporter/34px-Ritualist_Supporter.webp',
                'rarity' => '6★',
                'dp_cost' => 16,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Viviana_icon.webp',
                'name' => 'Viviana',
                'faction' => "images/factions/120px-Leithanien.webp",
                'class' => 'images/classes/50px-Guard.png',
                'archetype' => 'images/archetypes/guard/50px-Arts_Fighter_Guard.webp',
                'rarity' => '6★',
                'dp_cost' => 21,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Vulpisfoglia_icon.webp',
                'name' => 'Vulpisfoglia',
                'faction' => "images/factions/120px-Siracusa.webp",
                'class' => 'images/classes/50px-Vanguard.png',
                'archetype' => 'images/archetypes/vanguard/50px-Pioneer_Vanguard.webp',
                'rarity' => '6★',
                'dp_cost' => 14,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-W_icon.webp',
                'name' => 'W',
                'faction' => "images/factions/120px-Babel.webp",
                'class' => 'images/classes/50px-Sniper.png',
                'archetype' => 'images/archetypes/sniper/50px-Artilleryman_Sniper.webp',
                'rarity' => '6★',
                'dp_cost' => 29,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Weedy_icon.webp',
                'name' => 'Weedy',
                'faction' => "images/factions/120px-Rhodes_Island.webp",
                'class' => 'images/classes/50px-Specialist.png',
                'archetype' => 'images/archetypes/specialist/50px-Push_Stroker_Specialist.webp',
                'rarity' => '6★',
                'dp_cost' => 21,
            ],
            [
                'image' => "images/characters/rarity/6/100px-Wiš'adel_icon.webp",
                'name' => "Wis'adel",
                'faction' => "images/factions/120px-Babel.webp",
                'class' => 'images/classes/50px-Sniper.png',
                'archetype' => 'images/archetypes/sniper/50px-Flinger_Sniper.webp',
                'rarity' => '6★',
                'dp_cost' => 25,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Yu_icon.webp',
                'name' => 'Yu',
                'faction' => "images/factions/120px-Sui.webp",
                'class' => 'images/classes/49px-Defender.png',
                'archetype' => 'images/archetypes/defender/40px-Primal_Protector_Defender.webp',
                'rarity' => '6★',
                'dp_cost' => 26,
            ],
            [
                'image' => 'images/characters/rarity/6/100px-Zuo_Le_icon.webp',
                'name' => 'Zuo Le',
                'faction' => "images/factions/120px-Yan.webp",
                'class' => 'images/classes/50px-Guard.png',
                'archetype' => 'images/archetypes/guard/50px-Soloblade_Guard.webp',
                'rarity' => '6★',
                'dp_cost' => 26,
            ],
        ];

        foreach ($characters as $data) {
            Character::create($data);
        }
    }
}
